In [5]:
import numpy as np
arr=np.array([1,1,2,3,4,5])
print(np.append(arr,6)) #inserting a value at last

print(np.insert(arr,2,30)) #inserting value at specific index

print(np.delete(arr,[2]))  #delete items from at any index in an array



[1 1 2 3 4 5 6]
[ 1  1 30  2  3  4  5]
[1 1 3 4 5]
