In [7]:
import numpy as np
a=[[10,20,30],[30,40,50]]
arr=np.array(a)
print(arr)

#functions
print(arr.shape) #rows,columns
print(len(arr))  #number of nested values
print(np.size(arr))  #number of elements
print(type(arr)) #datatype of variable
print(arr.dtype) #datatype of array
print(arr.astype(float)) #conversion of datatype

[[10 20 30]
 [30 40 50]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[10. 20. 30.]
 [30. 40. 50.]]
