In [2]:
#array

import numpy as np 

arr=np.array([[10,20,30,40],[50,60,70,80]])

print(arr)
print(type(arr))



[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [9]:
#array slicing
arr=np.array([10,20,30,40,50])
print(arr[0:3])

arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(arr[1,0:3])

[10 20 30]
[50 60 70]


In [12]:
#array attributes or functions

arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(np.shape(arr))

print(np.size(arr))

print(np.ndim(arr))

print(arr.dtype)

(3, 4)
12
2
int64
