In [3]:
#array addition

import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1+arr2)
print(np.add(arr1,arr2))

arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1+arr2)

[ 60  80 100 120]
[ 60  80 100 120]
[[ 60  80]
 [100 120]]


In [7]:
#array subtraction

import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1-arr2)



[-40 -40 -40 -40]
[-40 -40 -40 -40]
[[-40 -40]
 [-40 -40]]


In [ ]:
#same for multipication and divide using both function and symbol

In [8]:
#for finding power and squre root of any array
arr1=([2,3,4,5])
arr2=([2])
print(np.power(arr1,arr2))


[ 4  9 16 25]


In [9]:
arr1=([4,9,16,25])
print(np.sqrt(arr1))

[2. 3. 4. 5.]
