In [8]:
#filter array
import numpy as np 
ar=np.array([20,30,40,50])
fa=[True,False,True,False]
new=ar[fa]
print(new)

fa=ar>=40
new=ar[fa]
print(new)

fa=ar%2==0
neww=ar[fa]
print(neww)

[20 40]
[40 50]
[20 30 40 50]


In [12]:
#sort and search
arr1=np.array([7,8,4,12,9])
print(np.sort(arr1))

s=np.where(arr1==4)     #it will returns the index value
print(s)

[ 4  7  8  9 12]
(array([2]),)
